# Generated by Django 3.1.4 on 2020-12-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201201_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ifsold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
