# Generated by Django 3.1.4 on 2020-12-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201201_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ifsold',
            new_name='sprzedany',
        ),
    ]
